### ISSUE TITLE
Joint Spectrum, Precoding, and Phase Shifts Design for RIS-Aided Multiuser MIMO THz Systems

### ISSUE THREAD

**Issue by mahdimathematics** [jwwthu/GNN-Communication-Networks#2]
Hi @jwwthu,
Our new paper is recently accepted to IEEE TCOM, introducing MHGphormer for Terahertz systems.
Here is the link for the paper and code.
https://ieeexplore.ieee.org/abstract/document/10472941
https://github.com/Ali-Meh619/MHGphormer

I appreciate it if you can include that in your github account.

Thanks,
Ali

**Comment by jwwthu** [comment]
Dear Ali,
Thanks for the recommendation. It would be added.
